name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone VAssistant, VAssist-Scrcpy, and EdgeTTS
      run: |
        git clone https://github.com/Vove7/VAssist-Scrcpy
        git clone https://github.com/Vove7/EdgeTTS
    - uses: actions/checkout@v3
    - name: Modify local.properties
      run: |
        echo "sdk.dir=...." >> local.properties
        echo "scrcpy-lib.dir=./VAssist-Scrcpy/common" >> local.properties
        echo "tts-lib.dir=./EdgeTTS/app" >> local.properties
      working-directory: ${{ github.workspace }}/
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
#     - name: Build with Gradle
#       uses: gradle/gradle-build-action@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ github.workspace }}

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ${{ github.workspace }}/
